<?php 
$ref = 'AdebarIROS2014';

$title = 'Recursive Estimation of Needle Pose for Control of 3D-Ultrasound-Guided Robotic Needle Steering';

$abstract = 'Robotic systems can improve percutaneous interventions by steering flexible needles along nonlinear trajectories. These systems require medical image feedback for accurate closed-loop control. Three-dimensional (3D) ultrasound can provide real-time measurements of needle pose within tissue; however, the ultrasound produces relatively large amounts of measurement noise. A recursive estimation approach is described for accurately estimating the six-degree-of-freedom pose of a steerable needle tip, by applying an unscented Kalman filter (UKF) to 3D ultrasound segmentation results. The UKF is formulated based on a kinematic process model of needle steering, as well as experimental quantification of the statistical variability of steering and imaging needles in biological tissue. Validation testing shows that the UKF method makes accurate closed-loop robotic control of the needle tip possible in biological tissue. Compared to direct use of noisy ultrasound data for control feedback, the UKF reduced average positioning error by 9.58 mm (81%) when steering towards a simulated target. This new estimation scheme will contribute towards the future evaluation of needle steering robots in realworld clinical applications.';

$algo = array(
	'Needle measurements generated by the Doppler ultrasound',
	'Tracking (Unscented KALMAN filter UKF) ',
	);

$result = array(
	'Average error &asymp; 2.69mm (VS 11.39mm whithout UKF)'
	);

include('abstract-summary.php');
?>