<?php 
$ref = 'doppler_basics';

$title = 'Localization of Needle Tip with Color Doppler During Pericardiocentesis: In Vitro Validation and Initial Clinical Application';

$abstract = 'This study evaluates a new device that uses color Doppler ultrasonography to enable real-time image guidance of the aspirating needle, which has not been possible until now. The ColorMark device (EchoCath Inc, Princeton, NJ) induces high-frequency, lowamplitude vibrations in the needle to enable localization with color Doppler. We studied this technique in 25 consecutive patients undergoing pericardiocentesis, and in vitro, in a urethane phantom with which the accuracy of color Doppler localization of the needle tip was compared with that obtained by direct measurement. Tip localization was excellent in vitro; errors axial to the ultrasound beam (velocity Doppler -0.13 + 0.90 mm; power Doppler -0.05 ± 1.7 mm) were less than lateral errors (velocity-O.36 ± 1.8 turn; power -0.02 + 2.8 mm). In 18 of 25 patients, the needle was identified and guided into the pericardial space with the ColorMark technique, and it allowed successful, uncomplicated drainage of fluid. Initial failures were the result of incorrect settings on the echocardiographic machine and inappropriate combinations of the needle puncture site and imaging window, This study demonstrates a novel color Doppler technique that is highly accurate at localizing a needle tip. The technique is feasible for guiding pericardiocentesis. Further clinical validation of this technique is required. ';

$algo = array(
	'Needle measurements generated by the Doppler ultrasound'
	);

$result = array(
	'Average error &asymp; -0.13 ±  0.90 mm'
	);

include('abstract-summary.php');
?>