<?php 
				$ref = 'GreerMICCAI2014';

				$title = 'Real-Time 3D Curved Needle Segmentation Using Combined B-Mode and Power Doppler Ultrasound';

				$abstract = 'This paper presents a real-time segmentation method for curved needles in biological tissue based on analysis of B-mode and power Doppler images from a tracked 2D ultrasound transducer. Mechanical vibration induced by an external voice coil results in a Doppler response along the needle shaft, which is centered around the needle section in the ultrasound image. First, B-mode image analysis is performed within regions of interest indicated by the Doppler response to create a segmentation of the needle section in the ultrasound image. Next, each needle section is decomposed into a sequence of points and transformed into a global coordinate system using the tracked transducer pose. Finally, the 3D shape is reconstructed from these points. The results of this method differ from manual segmentation by 0.71±0.55 mm in needle tip location and 0.38±0.27 mm along the needle shaft. This method is also fast, taking 5-10 ms to run on a standard PC, and is particularly advantageous in robotic needle steering, which involves thin, curved needles with poor echogenicity.';

				$algo = array(
					'ROI generated by the Doppler ultrasound',
					'Tracked 2D US probe',
					'Segmentation'
					);

				$result = array(
					'Average error &asymp; 0.71 ± 0.55 mm',
					'Computational time &asymp; 5-10 ms'
					);

				include('abstract-summary.php');
				?>